# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: demo-svcs

# resources:
#   - namespace.yaml
#   - service1-deployment.yaml
#   - service1-service.yaml
#   - service2-deployment.yaml
#   - service2-service.yaml
