apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: service1-allow-from-service2-only
  namespace: demo-svcs
spec:
  podSelector:
    matchLabels:
      app: service1
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: service2
